### ISSUE TITLE
Vat number is not validated on the billing address

### ISSUE THREAD

**Issue by thijsdewitt** [Vendic/hyva-checkout-geissweb-euvat#3]
### Steps to reproduce
1. Uncheck 'My billing and shipping address are the same'
2. Fill in the vat number

### Expected result
The vat number will be validated on the billing address

### Actual result
The vat number is not validated on the billing address

**Comment by Tjitse-E** [comment]
Closing, see https://github.com/Vendic/hyva-checkout-geissweb-euvat/pull/4#issuecomment-1772188715
