### ISSUE TITLE
Installation via composer is unfortunately not possible

### ISSUE THREAD

**Issue by in-session** [Vendic/hyva-checkout-geissweb-euvat#6]
We always get the error: "Could not find a matching version of package vendic/hyva-checkout-geissweb-euvat. Check the package notation, your version restriction and that the package is available in a stability that matches your minimum stability (stable)."

![image](https://github.com/Vendic/hyva-checkout-geissweb-euvat/assets/16542619/929a017b-a533-4ff1-9229-69b76adc4534)

hyva-themes/magento2-hyva-checkout                                1.1.6      
geissweb/module-euvat                                             1.20.9     
PHP 8.2

**Comment by Tjitse-E** [comment]
Thanks for opening an issue! You're correct, we forgot to add it to packagist.org. That's fixed now https://packagist.org/packages/vendic/hyva-checkout-geissweb-euvat. You should be able to install it via composer now.
